language: cpp
cache:
  directories:
  - node_modules
matrix:
  include:
  - os: osx
    env: _macos_build
    osx_image: xcode8.3
    before_install: "./CI/install-dependencies-macos.sh"
    script: "./CI/build-macos.sh"
    after_success:
    - "./CI/package-macos.sh"
# before_deploy:
  # Set up git user name and tag this commit
  # - git config --local user.name "Will Townsend"
  # - git config --local user.email "will@townsend.io"
  # - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: WSuSPQYQHH1jc8HtkPkElgmiEos2617xSGx8IMzWMRrerS2Ii7O8WMM8nY/msFuNmmf3AiTSatdxBZ5YBApCAQZqumWnLHxiNmwx5TVd0ojNd6TsoakcM3aleOiR7u16wXTNRJQjVlDYVJQhUztp9f9ReoMb+9iKHtJK+C5noVIrFRLqcTrzGxw5Viu8UWeA11t3/+OgDA62sRwZCVfUoQOTA6cTvRsdR2LF9tgkVOAtwGyvBLBQtDG0UWc2YFnOxnhm1w7m3EYBAxo7G+SORB1Ze70TxMsfqu6ZrUBdcnOPJ6ZbsEWxzmkCc6TSEl019MUmGuZ8JN+d4NGv5oiFLzGoeaNNpJ0bE2tIIE11p444IyixKSkV0wh/mT1yF4YPCDUUjxGh0u+iudfnx1Wj1adFm3GiBce/EajljyuTm7zrawSENLHVNdtl2X+vOSftKg3TeGYRxrWDwRo67l/5aHFS8NOMqiqh5lVs+URifAefIsAz5lAL5d6DVPqW1ipEbLnMrnAdlycpDP+x0e+dIbQHhXQUMr0HtiUgtEWylSihS8bE1CJpu5IMS9EMy0CJWP8QftkjDPnAZbM1JdJv83IepzFhGhbP4I33sQtMj/fh+QlzU/bDR9+Gpo0GV3gkTkvnK475QKcfaML0ConiRd50PrqXDhd6WjA3eUMuobs=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    repo: wtsnz/obs-ios-camera-source
    tags: true
    
